### PR TITLE
[Issue#147]Fix the bug of threadpool shutdown may be incomplete.

### LINKED ISSUE #147: 线程池退出时可能出现某些线程组未被调用thread_group_destroy的情况
https://github.com/kunpengcompute/mysql-server/commit/ebd0986af5adcb1563b236f0b057b9506760f81f#r55623061
线程池退出时可能出现某些线程组未被调用thread_group_destroy的情况

### PR DESCRIPTION
**Pull request by nbuxrr**
#147 In old code, when thread_count is zero we destroy the thread group. Then we move the destroy operation to a concentrated place to reduce delay. But we just return when thread_count is zero, which may lead to incompleted threadpool shutdown. In new code, we set shutdown flag before judging whether thread_count is zero to fix the bug.

### CODE REVIEW

**Comment by nbuxrr** [comment]
> Thanks for your pull request. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> The following commits have not yet signed CLA.
> 
> **[95f1d0e](https://github.com/kunpengcompute/mysql-server/commit/95f1d0e2893c4c9c1c55fd7ca2a3d1d248d5dd8f)** | Fix the bug of threadpool shutdown may be incomplete.
> 
> 📝 **Please access [here](https://clasign.osinfra.cn/sign/Z2l0aHViJTJGa3VucGVuZ2NvbXB1dGU=) to sign the CLA.**
> 
> It may take a couple minutes for the CLA signature to be fully registered; after that, please reply here with a new comment: **/check-cla** to verify. Thanks.
> 
> * If you've already signed a CLA, it's possible you're using a different email address for your gitee account. Check your existing CLA data and verify the email.
> * If you signed the CLA as an employee or a member of an organization, please contact your corporation or organization to verify you have been activated to start contributing.
> * If you have done the above and are still having issues with the CLA being reported as unsigned, please feel free to file an issue.

/check-cla

**Review by zwang28 — APPROVED** [review]

File: sql/threadpool_unix.cc [hunk 1]
```diff
@@ -1028,14 +1028,13 @@ static void thread_group_close(thread_group_t *thread_group)
...
 
   mysql_mutex_lock(&thread_group->mutex);
+  thread_group->shutdown= true;
   if (thread_group->thread_count == 0) 
   {
     mysql_mutex_unlock(&thread_group->mutex);
     DBUG_VOID_RETURN;
   }
 
-  thread_group->shutdown= true;
```
Comment (PeterWeiWang) [inline sql/threadpool_unix.cc:1037]: =两边都留一空格

Comment (zhang-lujie) [reply sql/threadpool_unix.cc:1037]: =左侧未留空格是为了和代码块风格保持一致，因为该代码块风格并不完全统一，改为=两边都留空格的正常风格

Comment (nbuxrr) [reply sql/threadpool_unix.cc:1037]: 只移动了原始代码行的位置

**Review by liuwei-ck — APPROVED** [review]
